### ISSUE TITLE
Split by dir

### ISSUE THREAD

**Issue by barryvdh** [nu774/m4acut#4]
Is it possible to split files to a separate directory?

Eg. I have a folder with podcasts (POD1.m4a, POD2.m4a etc), and I want to split the entire dir (perhaps with a simple batch for loop), but can I set the output folder? So like this:

POD1/01 First track.m4a
POD1/02 Second track.m4a
POD2/01 First track.m4a

Instead of all in the same folder.

**Comment by nu774** [comment]
Output of m4acut goes to the current directory.
Therefore, if you are using batch loop, try something like the following inside the loop:
```
mkdir POD1 && cd POD1 && m4acut -c ../POD1.m4a && cd ..
```

**Comment by barryvdh** [comment]
Yes I have it fixed now :)

```
for %%f in (*.m4a) DO (
	mkdir "%%~nf"
	copy  "%%f" "%%~nf\%%f"
	cd "%%~nf"
	m4acut -c "%%f"
	del "%%f"
	cd ..
)
pause
```
(Copies all .m4a files to directory without extension, runs the split, deletes the copy and returns)

Thanks!

**Comment by barryvdh** [comment]
Oh, no need it then indeed.
